name: Build and Deploy Client MS Stage

on:
  push:
    branches:
      - 'stage'
    paths:
      - 'client-ms/**'
      - 'common/**'
      - '.secrets/client-ms.**'
      - '.github/workflows/template_**.yml'
      - '.github/workflows/deploy_client-ms.yml'

jobs:
  healthcheck:
    needs: []
    uses: appleboy/ssh-action@master 
    env: 
      SERVER_PORT: 8001 
    with: 
      VPS_HOST: ${{ secrets.VPS_HOST_INTERNAL }} 
      VPS_USERNAME: ${{ secrets.VPS_USERNAME_INTERNAL }} 
      VPS_PASSWORD: ${{ secrets.VPS_PASSWORD_INTERNAL }} 
      SCRIPT: |
        script_output=$(bash /root/healthchecks/healthcheck-script.sh $SERVER_PORT) 
        echo "$script_output" 
        if [ $? -eq 0 ]; then 
          echo "::set-output name=status::success" 
        else 
          echo "::set-output name=status::failure" 
        fi